DRAGON_BLUEPRINTS = [
    { 'name': 'Qineg', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Ianir', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Dyghyg', 'nature': 'Fire', 'level': 15, 'power_level': 9 },
    { 'name': 'Caddrien', 'nature': 'Fire', 'level': 16, 'power_level': 9 },
    { 'name': 'Kolzrom', 'nature': 'Fire', 'level': 20, 'power_level': 10 },
    { 'name': 'Gryndes', 'nature': 'Fire', 'level': 20, 'power_level': 11 },
    { 'name': 'Rurgeg', 'nature': 'Fire', 'level': 21, 'power_level': 12 },
    { 'name': 'Relzroidis', 'nature': 'Fire', 'level': 21, 'power_level': 13 },
    { 'name': 'Ylredus', 'nature': 'Fire', 'level': 24, 'power_level': 12 },
    { 'name': 'Xighodam', 'nature': 'Fire', 'level': 26, 'power_level': 10 },
    { 'name': 'Bazagazeal', 'nature': 'Fire', 'level': 33, 'power_level': 30 },

    { 'name': 'Daydhaess', 'nature': 'Water', 'level': 7, 'power_level': 5 },
    { 'name': 'Aymraig', 'nature': 'Water', 'level': 6, 'power_level': 5 },
    { 'name': 'Zokio', 'nature': 'Water', 'level': 12, 'power_level': 7 },
    { 'name': 'Eomron', 'nature': 'Water', 'level': 14, 'power_level': 8 },
    { 'name': 'Maivroi', 'nature': 'Water', 'level': 18, 'power_level': 9 },
    { 'name': 'Baennaet', 'nature': 'Water', 'level': 20, 'power_level': 11 },
    { 'name': 'Movnaynth', 'nature': 'Water', 'level': 21, 'power_level': 11 },
    { 'name': 'Caldroinar', 'nature': 'Water', 'level': 22, 'power_level': 11 },
    { 'name': 'Ylredus', 'nature': 'Water', 'level': 23, 'power_level': 12 },
    { 'name': 'Tarsaydyth', 'nature': 'Water', 'level': 24, 'power_level': 10 },
    { 'name': 'Dailong', 'nature': 'Water', 'level': 27, 'power_level': 33 },
]
