DRAGON_BLUEPRINTS_1 = [
    { 'name': 'Qineg', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Ianir', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Dyghyg', 'nature': 'Fire', 'level': 15, 'power_level': 9 },
    { 'name': 'Caddrien', 'nature': 'Fire', 'level': 16, 'power_level': 9 },
    { 'name': 'Kolzrom', 'nature': 'Fire', 'level': 20, 'power_level': 10 },
    { 'name': 'Gryndes', 'nature': 'Fire', 'level': 20, 'power_level': 11 },
    { 'name': 'Rurgeg', 'nature': 'Fire', 'level': 21, 'power_level': 12 },
    { 'name': 'Relzroidis', 'nature': 'Fire', 'level': 21, 'power_level': 13 },
    { 'name': 'Ylredus', 'nature': 'Fire', 'level': 24, 'power_level': 12 },
    { 'name': 'Xighodam', 'nature': 'Fire', 'level': 26, 'power_level': 10 },
    { 'name': 'Bazagazeal', 'nature': 'Fire', 'level': 33, 'power_level': 30 },

    { 'name': 'Daydhaess', 'nature': 'Water', 'level': 7, 'power_level': 5 },
    { 'name': 'Aymraig', 'nature': 'Water', 'level': 6, 'power_level': 5 },
    { 'name': 'Zokio', 'nature': 'Water', 'level': 12, 'power_level': 7 },
    { 'name': 'Eomron', 'nature': 'Water', 'level': 14, 'power_level': 8 },
    { 'name': 'Maivroi', 'nature': 'Water', 'level': 18, 'power_level': 9 },
    { 'name': 'Baennaet', 'nature': 'Water', 'level': 20, 'power_level': 11 },
    { 'name': 'Movnaynth', 'nature': 'Water', 'level': 21, 'power_level': 11 },
    { 'name': 'Caldroinar', 'nature': 'Water', 'level': 22, 'power_level': 11 },
    { 'name': 'Ylredus', 'nature': 'Water', 'level': 23, 'power_level': 12 },
    { 'name': 'Tarsaydyth', 'nature': 'Water', 'level': 24, 'power_level': 10 },
    { 'name': 'Dailong', 'nature': 'Water', 'level': 27, 'power_level': 33 },

    { 'name': 'Frairmyss', 'nature': 'Wind', 'level': 2, 'power_level': 2 },
    { 'name': 'Oizoanth', 'nature': 'Wind', 'level': 4, 'power_level': 3 },
    { 'name': 'Qoitirth', 'nature': 'Wind', 'level': 7, 'power_level': 4 },
    { 'name': 'Iorvug', 'nature': 'Wind', 'level': 8, 'power_level': 3 },
    { 'name': 'Vileilth', 'nature': 'Wind', 'level': 15, 'power_level': 9 },
    { 'name': 'Yndios', 'nature': 'Wind', 'level': 17, 'power_level': 11 },
    { 'name': 'Seozzure', 'nature': 'Wind', 'level': 25, 'power_level': 12 },
    { 'name': 'Gayrvudael', 'nature': 'Wind', 'level': 27, 'power_level': 15 },
    { 'name': 'Frugaylun', 'nature': 'Wind', 'level': 31, 'power_level': 15 },
    { 'name': 'Zirry', 'nature': 'Wind', 'level': 34, 'power_level': 21 },
    { 'name': 'Hunter', 'nature': 'Wind', 'level': 40, 'power_level': 40 },

    { 'name': 'Cyrvi', 'nature': 'Earth', 'level': 3, 'power_level': 2 },
    { 'name': 'Vizza', 'nature': 'Earth', 'level': 7, 'power_level': 3 },
    { 'name': 'Norvael', 'nature': 'Earth', 'level': 11, 'power_level': 4 },
    { 'name': 'Qyldran', 'nature': 'Earth', 'level': 12, 'power_level': 3 },
    { 'name': 'Cargith', 'nature': 'Earth', 'level': 15, 'power_level': 9 },
    { 'name': 'Iophyrth', 'nature': 'Earth', 'level': 17, 'power_level': 11 },
    { 'name': 'Mossiphylth', 'nature': 'Earth', 'level': 22, 'power_level': 12 },
    { 'name': 'Unnessuth', 'nature': 'Earth', 'level': 23, 'power_level': 15 },
    { 'name': 'Ysurra', 'nature': 'Earth', 'level': 28, 'power_level': 15 },
    { 'name': 'Rydarth', 'nature': 'Earth', 'level': 31, 'power_level': 21 },
    { 'name': 'Baron Seemedi', 'nature': 'Earth', 'level': 36, 'power_level': 40 },

    { 'name': 'Andrew', 'nature': 'Fire', 'level': 1225, 'power_level': 125 },
    { 'name': 'ScarluX', 'nature': 'Wind', 'level': 66, 'power_level': 55 },
    { 'name': 'Game [test]', 'nature': 'Earth', 'level': 100, 'power_level': 100 },
    { 'name': 'ÅŤζÅÑŤЇŞ', 'nature': 'Water', 'level': 80, 'power_level': 66 },
    { 'name': '-=Saneyewz=-', 'nature': 'Wind', 'level': 127, 'power_level': 80 },
    { 'name': 'Regret.', 'nature': 'Fire', 'level': 600, 'power_level': 220 },
]

DRAGON_BLUEPRINTS_2 = [
    { 'name': 'Hipa', 'nature': 'Fire', 'level': 1, 'power_level': 1},
    { 'name': 'Crokliox', 'nature': 'Fire', 'level': 5, 'power_level': 4 },
    { 'name': 'Anubrourm', 'nature': 'Fire', 'level': 28, 'power_level': 25 },
    { 'name': 'Abachdroa', 'nature': 'Fire', 'level': 29, 'power_level': 20 },
    { 'name': 'Medusqie', 'nature': 'Fire', 'level': 33, 'power_level': 25 },
    { 'name': 'Joshinod', 'nature': 'Fire', 'level': 35, 'power_level': 30 },
    { 'name': 'Raokie', 'nature': 'Fire', 'level': 39, 'power_level': 28 },
    { 'name': 'Cager', 'nature': 'Fire', 'level': 40, 'power_level': 30 },
    { 'name': 'Ameg', 'nature': 'Fire', 'level': 41, 'power_level': 30 },
    { 'name': 'Couconut', 'nature': 'Fire', 'level': 44, 'power_level': 20 },
    { 'name': 'SUPERNOVA', 'nature': 'Fire', 'level': 49, 'power_level': 50 },

    { 'name': 'AquA', 'nature': 'Water', 'level': 3, 'power_level': 1 },
    { 'name': 'Anunund', 'nature': 'Water', 'level': 6, 'power_level': 2 },
    { 'name': 'Lamruff', 'nature': 'Water', 'level': 27, 'power_level': 19 },
    { 'name': 'Pegarpux', 'nature': 'Water', 'level': 29, 'power_level': 20 },
    { 'name': 'Lncuceir', 'nature': 'Water', 'level': 31, 'power_level': 22 },
    { 'name': 'Tavato', 'nature': 'Water', 'level': 33, 'power_level': 25 },
    { 'name': 'Ueron', 'nature': 'Water', 'level': 36, 'power_level': 29 },
    { 'name': 'Seren', 'nature': 'Water', 'level': 40, 'power_level': 30 },
    { 'name': 'Oofin', 'nature': 'Water', 'level': 42, 'power_level': 32 },
    { 'name': 'Gargamel', 'nature': 'Water', 'level': 43, 'power_level': 25 },
    { 'name': 'Onizuka', 'nature': 'Water', 'level': 45, 'power_level': 49 },

    { 'name': 'Aklocleo', 'nature': 'Wind', 'level': 1, 'power_level': 1 },
    { 'name': 'Proxima', 'nature': 'Wind', 'level': 3, 'power_level': 1 },
    { 'name': 'Sicedionx', 'nature': 'Wind', 'level': 12, 'power_level': 5 },
    { 'name': 'Gmalou', 'nature': 'Wind', 'level': 13, 'power_level': 9 },
    { 'name': 'Saigeur', 'nature': 'Wind', 'level': 31, 'power_level': 21 },
    { 'name': 'Jouberus', 'nature': 'Wind', 'level': 33, 'power_level': 22 },
    { 'name': 'Scuesu', 'nature': 'Wind', 'level': 39, 'power_level': 33 },
    { 'name': 'Ceahorn', 'nature': 'Wind', 'level': 44, 'power_level': 33 },
    { 'name': 'Frugaylun', 'nature': 'Wind', 'level': 47, 'power_level': 39 },
    { 'name': 'Beilisd', 'nature': 'Wind', 'level': 50, 'power_level': 40 },
    { 'name': 'Neuron', 'nature': 'Wind', 'level': 52, 'power_level': 50 },

    { 'name': 'Cyrvi', 'nature': 'Earth', 'level': 3, 'power_level': 1 },
    { 'name': 'Vizza', 'nature': 'Earth', 'level': 7, 'power_level': 2 },
    { 'name': 'Norvael', 'nature': 'Earth', 'level': 34, 'power_level': 24 },
    { 'name': 'Qyldran', 'nature': 'Earth', 'level': 36, 'power_level': 26 },
    { 'name': 'Cargith', 'nature': 'Earth', 'level': 39, 'power_level': 28 },
    { 'name': 'Iophyrth', 'nature': 'Earth', 'level': 44, 'power_level': 30 },
    { 'name': 'Mossiphylth', 'nature': 'Earth', 'level': 47, 'power_level': 34 },
    { 'name': 'Unnessuth', 'nature': 'Earth', 'level': 48, 'power_level': 35 },
    { 'name': 'Ysurra', 'nature': 'Earth', 'level': 51, 'power_level': 35 },
    { 'name': 'Rydarth', 'nature': 'Earth', 'level': 55, 'power_level': 32 },
    { 'name': 'Titan X', 'nature': 'Earth', 'level': 60, 'power_level': 50 },

    { 'name': 'El Padro', 'nature': 'Fire', 'level': 100, 'power_level': 80 },
    { 'name': 'Koper', 'nature': 'Wind', 'level': 63, 'power_level': 55 },
    { 'name': 'Nightwood', 'nature': 'Earth', 'level': 99, 'power_level': 77 },
    { 'name': 'Szach', 'nature': 'Water', 'level': 80, 'power_level': 70 },
    { 'name': 'Kubano', 'nature': 'Wind', 'level': 200, 'power_level': 99 },
    { 'name': 'Mystery.', 'nature': 'Water', 'level': 300, 'power_level': 123 },
]
