DRAGON_BLUEPRINTS = [
    { 'name': 'Qineg', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Ianir', 'nature': 'Fire', 'level': 10, 'power_level': 5 },
    { 'name': 'Dyghyg', 'nature': 'Fire', 'level': 15, 'power_level': 9 },
    { 'name': 'Caddrien', 'nature': 'Fire', 'level': 16, 'power_level': 9 },
    { 'name': 'Kolzrom', 'nature': 'Fire', 'level': 20, 'power_level': 10 },
    { 'name': 'Gryndes', 'nature': 'Fire', 'level': 20, 'power_level': 11 },
    { 'name': 'Rurgeg', 'nature': 'Fire', 'level': 21, 'power_level': 12 },
    { 'name': 'Relzroidis', 'nature': 'Fire', 'level': 21, 'power_level': 13 },
    { 'name': 'Ylredus', 'nature': 'Fire', 'level': 24, 'power_level': 12 },
    { 'name': 'Xighodam', 'nature': 'Fire', 'level': 26, 'power_level': 10 },
    { 'name': 'Bazagazeal', 'nature': 'Fire', 'level': 33, 'power_level': 30 },

    { 'name': 'Daydhaess', 'nature': 'Water', 'level': 7, 'power_level': 5 },
    { 'name': 'Aymraig', 'nature': 'Water', 'level': 6, 'power_level': 5 },
    { 'name': 'Zokio', 'nature': 'Water', 'level': 12, 'power_level': 7 },
    { 'name': 'Eomron', 'nature': 'Water', 'level': 14, 'power_level': 8 },
    { 'name': 'Maivroi', 'nature': 'Water', 'level': 18, 'power_level': 9 },
    { 'name': 'Baennaet', 'nature': 'Water', 'level': 20, 'power_level': 11 },
    { 'name': 'Movnaynth', 'nature': 'Water', 'level': 21, 'power_level': 11 },
    { 'name': 'Caldroinar', 'nature': 'Water', 'level': 22, 'power_level': 11 },
    { 'name': 'Ylredus', 'nature': 'Water', 'level': 23, 'power_level': 12 },
    { 'name': 'Tarsaydyth', 'nature': 'Water', 'level': 24, 'power_level': 10 },
    { 'name': 'Dailong', 'nature': 'Water', 'level': 27, 'power_level': 33 },

    { 'name': 'Frairmyss', 'nature': 'Wind', 'level': 2, 'power_level': 2 },
    { 'name': 'Oizoanth', 'nature': 'Wind', 'level': 4, 'power_level': 3 },
    { 'name': 'Qoitirth', 'nature': 'Wind', 'level': 7, 'power_level': 4 },
    { 'name': 'Iorvug', 'nature': 'Wind', 'level': 8, 'power_level': 3 },
    { 'name': 'Vileilth', 'nature': 'Wind', 'level': 15, 'power_level': 9 },
    { 'name': 'Yndios', 'nature': 'Wind', 'level': 17, 'power_level': 11 },
    { 'name': 'Seozzure', 'nature': 'Wind', 'level': 25, 'power_level': 12 },
    { 'name': 'Gayrvudael', 'nature': 'Wind', 'level': 27, 'power_level': 15 },
    { 'name': 'Frugaylun', 'nature': 'Wind', 'level': 31, 'power_level': 15 },
    { 'name': 'Zirry', 'nature': 'Wind', 'level': 34, 'power_level': 21 },
    { 'name': 'Hunter', 'nature': 'Wind', 'level': 40, 'power_level': 40 },

    { 'name': 'Cyrvi', 'nature': 'Earth', 'level': 3, 'power_level': 2 },
    { 'name': 'Vizza', 'nature': 'Earth', 'level': 7, 'power_level': 3 },
    { 'name': 'Norvael', 'nature': 'Earth', 'level': 11, 'power_level': 4 },
    { 'name': 'Qyldran', 'nature': 'Earth', 'level': 12, 'power_level': 3 },
    { 'name': 'Cargith', 'nature': 'Earth', 'level': 15, 'power_level': 9 },
    { 'name': 'Iophyrth', 'nature': 'Earth', 'level': 17, 'power_level': 11 },
    { 'name': 'Mossiphylth', 'nature': 'Earth', 'level': 22, 'power_level': 12 },
    { 'name': 'Unnessuth', 'nature': 'Earth', 'level': 23, 'power_level': 15 },
    { 'name': 'Ysurra', 'nature': 'Earth', 'level': 28, 'power_level': 15 },
    { 'name': 'Rydarth', 'nature': 'Earth', 'level': 31, 'power_level': 21 },
    { 'name': 'Baron Seemedi', 'nature': 'Earth', 'level': 36, 'power_level': 40 },

    { 'name': 'Andrew', 'nature': 'Fire', 'level': 1225, 'power_level': 125 },
    { 'name': 'ScarluX', 'nature': 'Wind', 'level': 66, 'power_level': 55 },
    { 'name': 'Game [test]', 'nature': 'Earth', 'level': 100, 'power_level': 100 },
    { 'name': 'ÅŤζÅÑŤЇŞ', 'nature': 'Water', 'level': 80, 'power_level': 66 },
    { 'name': '-=Saneyewz=-', 'nature': 'Wind', 'level': 127, 'power_level': 80 },
    { 'name': 'Regret.', 'nature': 'Fire', 'level': 600, 'power_level': 220 },
]
